# Generated by Django 5.2.7 on 2025-10-07 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('code_snippet', models.TextField(blank=True, verbose_name='کُد نمونه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='عکس (اختیاری)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
