# Generated by Django 5.2.7 on 2025-10-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(choices=[('programming-basics', 'مبانی برنامه\u200cنویسی'), ('basic-data-structures', 'ساختار داده\u200cهای پایه'), ('stack-and-queue', 'پشته و صف'), ('hash-tables', 'جداول هش / دیکشنری'), ('recursion-and-sorting', 'بازگشتی و مرتب\u200cسازی'), ('trees-and-graphs', 'درخت\u200cها و گراف\u200cها'), ('advanced-data-structures', 'ساختار داده\u200cهای پیشرفته'), ('algorithms-and-problem-solving', 'الگوریتم\u200cها و حل مسئله'), ('problem-solving-patterns', 'الگوهای حل مسئله'), ('practice-and-competitions', 'تمرین و مسابقات برنامه\u200cنویسی')], default='other', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
    ]
