# Generated by Django 5.2.7 on 2025-10-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='author',
            field=models.CharField(default='Admin', max_length=100, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.CharField(choices=[('basics', 'مبانی'), ('data_structures', 'ساختارهای داده'), ('algorithms', 'الگوریتم\u200cها'), ('interviews', 'مصاحبه\u200cها'), ('other', 'سایر')], default='other', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
    ]
